### ISSUE TITLE
Issues about use_esm and file during running

### ISSUE THREAD

**Issue by TheLZY** [hanrthu/GMSL#7]
First, 'BaseModel' object has no attribute 'use_esm'

```
(gmsl) (base) zlin29@teslal40s:~/github_repo/GMSL$ python -W ignore train.py --config ./config/gmsl_gearnet_train_all.yaml
Global seed set to 817
Starting run 0 with seed 817
Initializing MultiTask Model...
Traceback (most recent call last):
  File "/home/zlin29/github_repo/GMSL/train.py", line 113, in <module>
    model = model_cls(**args.model_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zlin29/github_repo/GMSL/utils/task_models.py", line 69, in __init__
    self.model = BaseModel(sdim=sdim,
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/zlin29/github_repo/GMSL/gmsl/model.py", line 96, in __init__
    if self.use_esm:
       ^^^^^^^^^^^^
  File "/home/zlin29/softwares/anaconda3/envs/gmsl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BaseModel' object has no attribute 'use_esm'
```

after mannually adding that attribute, I encountered with another issue about data:

```
(gmsl) (base) zlin29@teslal40s:~/github_repo/GMSL$ python -W ignore train.py --config ./config/gmsl_gearnet_train_all.yaml
Global seed set to 817
Starting run 0 with seed 817
Initializing MultiTask Model...

......

File "/home/zlin29/github_repo/GMSL/utils/datamodule.py", line 128, in __init__
**FileNotFoundError: [Errno 2] No such file or directory: './datasets/MultiTask_train_all'**

```

In datamodule.py, the files are searched using folder `graph_cache_dir`_`train` instead of `train.cache` in provided file
[Multitask.tar.gz](https://cloud.tsinghua.edu.cn/f/bb33cdeaf780472cb8ad/)

https://github.com/hanrthu/GMSL/blob/98eef2e4c379e42e945369b48a52fabc72e8fe79/utils/datamodule.py#L127-L128

**Comment by hanrthu** [comment]
Thank you for your attention to our work. The error comes from the mismatch of codes and the dataset. And we will update the dataset and codes soon.
